#!/bin/bash

function buildFonts {
  SRC="$1"
  echo "Processing ${SRC} folder..."
  for src in $(ls -d ${SRC}/*.sfdir); do
    dn="$(dirname $src)"
    bfn="$(basename $src .sfdir)"
    bnsrc="$dn/$bfn"
    echo "Building ${bfn}..."
    fontforge -script makeFontRelease.py $bnsrc
  done
}

buildFonts "src"

echo "DONE"
